version: '3.8'

services:
  back-end:
    build: ./back-end
    # No public ports!
    expose:
      - "5252"

  front-end:
    build: ./front-end
    # No public ports!
    expose:
      - "9000"

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
